# Generated by Django 5.1.6 on 2025-02-23 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20250222_1932'),
        ('users', '0004_auto_20250223_0835'),
    ]

    operations = [
    ]
