# Generated by Django 5.1.6 on 2025-02-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='upload',
        ),
    ]
