services:
  - type: web
    name: skillifyi
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput --clear
      python manage.py migrate
    startCommand: gunicorn skillifyi_backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DJANGO_SECRET_KEY
        value: django-insecure-dl8^adh%=$j*c3r@0qr6f*$6@4+t3)_9gh-65ky*@8_6g_o&(^
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        value: postgresql://root:O0PjVon7y55LffXO8AWCweIPp8c9jSZp@dpg-cvkj63d6ubrc73fpknu0-a.oregon-postgres.render.com/skillifyidb
      - key: ALLOWED_HOSTS
        value: "*,.onrender.com,skillifyi.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com,https://skillifyi.onrender.com
      - key: SECURE_SSL_REDIRECT
        value: False
      - key: SESSION_COOKIE_SECURE
        value: False
      - key: CSRF_COOKIE_SECURE
        value: False
      - key: SECURE_CONTENT_TYPE_NOSNIFF
        value: False 