services:
  - type: web
    name: skillifyi
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash setup.sh && gunicorn skillifyi_backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DJANGO_SECRET_KEY
        value: django-insecure-dl8^adh%=$j*c3r@0qr6f*$6@4+t3)_9gh-65ky*@8_6g_o&(^
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: skillifyi-db
          property: connectionString 